global:
  resolve_timeout: 5m

route:
  receiver: "default-alerts"
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 30m

  routes:
    - matchers:
        - severity="critical"
      receiver: "critical-alerts"

receivers:

  - name: "default-alerts"
    webhook_configs:
      - url: "https://emailwebhook-production-9d4c.up.railway.app/alert"
        send_resolved: true

  - name: "critical-alerts"
    webhook_configs:
      - url: "https://emailwebhook-production-9d4c.up.railway.app/alert/critical"
        send_resolved: true
