global:
  resolve_timeout: 5m
  smtp_smarthost: "smtp.sendgrid.net:25"
  smtp_from: "planeteyefarm@gmail.com"
  smtp_auth_username: "apikey"
  smtp_auth_password: "${SMTP_PASSWORD}"
  smtp_require_tls: true

route:
  receiver: "default-alerts"
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

  routes:
    - matchers:
        - severity="critical"
      receiver: "critical-alerts"

receivers:

  - name: "default-alerts"
    email_configs:
      - to: "Aniket.Shinde@planeteyefarm.ai"
        send_resolved: true

  - name: "critical-alerts"
    email_configs:
      - to: "tushar.patil@mitconindia.com,ram.thakur@planeteyeinfra.ai,sahil.sonawane@planeteyefarm.ai,snigdha.take@planeteyefarm.ai,Kalyani.Pawar@planeteyefarm.ai"
        send_resolved: true
